unit nsDOMEvent;

interface

uses nsTypes, nsXPCOM, nsGeckoStrings;

const
  NS_IDOMKEYEVENT_IID: TGUID = '{028e0e6e-8b01-11d3-aae7-0010838a3123}';
  NS_IDOMKEYEVENT_DOM_VK_CANCEL = 3;
  NS_IDOMKEYEVENT_DOM_VK_HELP = 6;
  NS_IDOMKEYEVENT_DOM_VK_BACK_SPACE = 8;
  NS_IDOMKEYEVENT_DOM_VK_TAB = 9;
  NS_IDOMKEYEVENT_DOM_VK_CLEAR = 12;
  NS_IDOMKEYEVENT_DOM_VK_RETURN = 13;
  NS_IDOMKEYEVENT_DOM_VK_ENTER = 14;
  NS_IDOMKEYEVENT_DOM_VK_SHIFT = 16;
  NS_IDOMKEYEVENT_DOM_VK_CONTROL = 17;
  NS_IDOMKEYEVENT_DOM_VK_ALT = 18;
  NS_IDOMKEYEVENT_DOM_VK_PAUSE = 19;
  NS_IDOMKEYEVENT_DOM_VK_CAPS_LOCK = 20;
  NS_IDOMKEYEVENT_DOM_VK_ESCAPE = 27;
  NS_IDOMKEYEVENT_DOM_VK_SPACE = 32;
  NS_IDOMKEYEVENT_DOM_VK_PAGE_UP = 33;
  NS_IDOMKEYEVENT_DOM_VK_PAGE_DOWN = 34;
  NS_IDOMKEYEVENT_DOM_VK_END = 35;
  NS_IDOMKEYEVENT_DOM_VK_HOME = 36;
  NS_IDOMKEYEVENT_DOM_VK_LEFT = 37;
  NS_IDOMKEYEVENT_DOM_VK_UP = 38;
  NS_IDOMKEYEVENT_DOM_VK_RIGHT = 39;
  NS_IDOMKEYEVENT_DOM_VK_DOWN = 40;
  NS_IDOMKEYEVENT_DOM_VK_PRINTSCREEN = 44;
  NS_IDOMKEYEVENT_DOM_VK_INSERT = 45;
  NS_IDOMKEYEVENT_DOM_VK_DELETE = 46;
  NS_IDOMKEYEVENT_DOM_VK_0 = 48;
  NS_IDOMKEYEVENT_DOM_VK_1 = 49;
  NS_IDOMKEYEVENT_DOM_VK_2 = 50;
  NS_IDOMKEYEVENT_DOM_VK_3 = 51;
  NS_IDOMKEYEVENT_DOM_VK_4 = 52;
  NS_IDOMKEYEVENT_DOM_VK_5 = 53;
  NS_IDOMKEYEVENT_DOM_VK_6 = 54;
  NS_IDOMKEYEVENT_DOM_VK_7 = 55;
  NS_IDOMKEYEVENT_DOM_VK_8 = 56;
  NS_IDOMKEYEVENT_DOM_VK_9 = 57;
  NS_IDOMKEYEVENT_DOM_VK_SEMICOLON = 59;
  NS_IDOMKEYEVENT_DOM_VK_EQUALS = 61;
  NS_IDOMKEYEVENT_DOM_VK_A = 65;
  NS_IDOMKEYEVENT_DOM_VK_B = 66;
  NS_IDOMKEYEVENT_DOM_VK_C = 67;
  NS_IDOMKEYEVENT_DOM_VK_D = 68;
  NS_IDOMKEYEVENT_DOM_VK_E = 69;
  NS_IDOMKEYEVENT_DOM_VK_F = 70;
  NS_IDOMKEYEVENT_DOM_VK_G = 71;
  NS_IDOMKEYEVENT_DOM_VK_H = 72;
  NS_IDOMKEYEVENT_DOM_VK_I = 73;
  NS_IDOMKEYEVENT_DOM_VK_J = 74;
  NS_IDOMKEYEVENT_DOM_VK_K = 75;
  NS_IDOMKEYEVENT_DOM_VK_L = 76;
  NS_IDOMKEYEVENT_DOM_VK_M = 77;
  NS_IDOMKEYEVENT_DOM_VK_N = 78;
  NS_IDOMKEYEVENT_DOM_VK_O = 79;
  NS_IDOMKEYEVENT_DOM_VK_P = 80;
  NS_IDOMKEYEVENT_DOM_VK_Q = 81;
  NS_IDOMKEYEVENT_DOM_VK_R = 82;
  NS_IDOMKEYEVENT_DOM_VK_S = 83;
  NS_IDOMKEYEVENT_DOM_VK_T = 84;
  NS_IDOMKEYEVENT_DOM_VK_U = 85;
  NS_IDOMKEYEVENT_DOM_VK_V = 86;
  NS_IDOMKEYEVENT_DOM_VK_W = 87;
  NS_IDOMKEYEVENT_DOM_VK_X = 88;
  NS_IDOMKEYEVENT_DOM_VK_Y = 89;
  NS_IDOMKEYEVENT_DOM_VK_Z = 90;
  NS_IDOMKEYEVENT_DOM_VK_CONTEXT_MENU = 93;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD0 = 96;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD1 = 97;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD2 = 98;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD3 = 99;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD4 = 100;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD5 = 101;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD6 = 102;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD7 = 103;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD8 = 104;
  NS_IDOMKEYEVENT_DOM_VK_NUMPAD9 = 105;
  NS_IDOMKEYEVENT_DOM_VK_MULTIPLY = 106;
  NS_IDOMKEYEVENT_DOM_VK_ADD = 107;
  NS_IDOMKEYEVENT_DOM_VK_SEPARATOR = 108;
  NS_IDOMKEYEVENT_DOM_VK_SUBTRACT = 109;
  NS_IDOMKEYEVENT_DOM_VK_DECIMAL = 110;
  NS_IDOMKEYEVENT_DOM_VK_DIVIDE = 111;
  NS_IDOMKEYEVENT_DOM_VK_F1 = 112;
  NS_IDOMKEYEVENT_DOM_VK_F2 = 113;
  NS_IDOMKEYEVENT_DOM_VK_F3 = 114;
  NS_IDOMKEYEVENT_DOM_VK_F4 = 115;
  NS_IDOMKEYEVENT_DOM_VK_F5 = 116;
  NS_IDOMKEYEVENT_DOM_VK_F6 = 117;
  NS_IDOMKEYEVENT_DOM_VK_F7 = 118;
  NS_IDOMKEYEVENT_DOM_VK_F8 = 119;
  NS_IDOMKEYEVENT_DOM_VK_F9 = 120;
  NS_IDOMKEYEVENT_DOM_VK_F10 = 121;
  NS_IDOMKEYEVENT_DOM_VK_F11 = 122;
  NS_IDOMKEYEVENT_DOM_VK_F12 = 123;
  NS_IDOMKEYEVENT_DOM_VK_F13 = 124;
  NS_IDOMKEYEVENT_DOM_VK_F14 = 125;
  NS_IDOMKEYEVENT_DOM_VK_F15 = 126;
  NS_IDOMKEYEVENT_DOM_VK_F16 = 127;
  NS_IDOMKEYEVENT_DOM_VK_F17 = 128;
  NS_IDOMKEYEVENT_DOM_VK_F18 = 129;
  NS_IDOMKEYEVENT_DOM_VK_F19 = 130;
  NS_IDOMKEYEVENT_DOM_VK_F20 = 131;
  NS_IDOMKEYEVENT_DOM_VK_F21 = 132;
  NS_IDOMKEYEVENT_DOM_VK_F22 = 133;
  NS_IDOMKEYEVENT_DOM_VK_F23 = 134;
  NS_IDOMKEYEVENT_DOM_VK_F24 = 135;
  NS_IDOMKEYEVENT_DOM_VK_NUM_LOCK = 144;
  NS_IDOMKEYEVENT_DOM_VK_SCROLL_LOCK = 145;
  NS_IDOMKEYEVENT_DOM_VK_COMMA = 188;
  NS_IDOMKEYEVENT_DOM_VK_PERIOD = 190;
  NS_IDOMKEYEVENT_DOM_VK_SLASH = 191;
  NS_IDOMKEYEVENT_DOM_VK_BACK_QUOTE = 192;
  NS_IDOMKEYEVENT_DOM_VK_OPEN_BRACKET = 219;
  NS_IDOMKEYEVENT_DOM_VK_BACK_SLASH = 220;
  NS_IDOMKEYEVENT_DOM_VK_CLOSE_BRACKET = 221;
  NS_IDOMKEYEVENT_DOM_VK_QUOTE = 222;
  NS_IDOMKEYEVENT_DOM_VK_META = 224;

type
  nsIDOMKeyEvent = interface;

  nsIDOMKeyEvent = interface(nsIDOMUIEvent)
  ['{028e0e6e-8b01-11d3-aae7-0010838a3123}']
    function GetCharCode(): PRUint32; safecall;
    property CharCode: PRUint32 read GetCharCode;
    function GetKeyCode(): PRUint32; safecall;
    property KeyCode: PRUint32 read GetKeyCode;
    function GetAltKey(): PRBool; safecall;
    property AltKey: PRBool read GetAltKey;
    function GetCtrlKey(): PRBool; safecall;
    property CtrlKey: PRBool read GetCtrlKey;
    function GetShiftKey(): PRBool; safecall;
    property ShiftKey: PRBool read GetShiftKey;
    function GetMetaKey(): PRBool; safecall;
    property MetaKey: PRBool read GetMetaKey;
    procedure InitKeyEvent(const typeArg: nsAString; canBubbleArg: PRBool; cancelableArg: PRBool; viewArg: nsIDOMAbstractView; ctrlKeyArg: PRBool; altKeyArg: PRBool; shiftKeyArg: PRBool; metaKeyArg: PRBool; keyCodeArg: PRUint32; charCodeArg: PRUint32); safecall;
  end;

implementation

end.
